name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display a message
      run: echo "Runner is working!"
